name: Greeting from Mona
on: push

env: 
  TZ: Asia/Shanghai
  DOUYIN-COOKIES: ${{ secrets.test }}
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps: 
      - name: checkout actions
        uses: actions/checkout@v3

      - name: set up python 3.9
        uses: actions/setup-python@v4
        with: 
          python-version : '3.9'

      - name: set up ffmpeg
        run: |
          tar xvf ./ffm/ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
          ln -s ./ffm/ffmpeg-n6.0-latest-linux64-gpl-6.0/ffmpeg /bin/ffmpeg

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      - name: set up node 14.8
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: running
        run: |
          pip install aligo

          git config --local user.email "git@qq.com"
          git config --local user.name "Ezong"
          mkdir -p ~/.aligo/
          python aa.py
          ls

      #     git commit -a -m "Add changes"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     branch: ${{ github.ref }}