name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps: 
    - name: Print a greeting
    - uses: actions/checkout@v3
    - run: |
        git -v
        ls -a
        echo ${{ secrets.test }}
